### ISSUE TITLE
fish_right_prompt not printing

### ISSUE THREAD

**Issue by GodTamIt** [oh-my-fish/theme-budspencer#47]
I'm having an issue with this theme where every function in fish_right_prompt.fish results in a `command not found` error:

For example, if I toggle into VI mode and press the spacebar, I end up with the following warning:
`__budspencer_toggle_pwd: command not found`

Any ideas?

**Comment by hawkeyej** [comment]
I'm having the same issue in WSL (Windows Subsystem for Linux). Very frustrating.

**Comment by AdwinKing** [comment]
I had the same problem.
You may have a look at /home/$USERNAME/.config/fish/functions/.
In my case I need to create soft links to files in /home/$USERNAME/.local/share/omf/themes/budspencer/

**Comment by clayauld** [comment]
This issue shows up on all Linux distros on WSL. The offending lines of code are located in the fish_right_prompt.fish file.

`# Automatically disables right prompt when in a tty
# Except in Darwin due to OS X terminals identifying themselves as a tty
if not test (uname) = Darwin
  if tty | grep tty >/dev/null
    exit
  end
end`

Apparently WSL also identifies itself as a tty, so an exemption has to be placed in the code for this as well. I'll be forking this repository with this fix since pull requests are not getting any response here.

**Comment by clayauld** [comment]
I've fixed the issue for WSL.
