### ISSUE TITLE
Functions throwing syntax errors

### ISSUE THREAD

**Issue by jscheel** [oh-my-fish/theme-budspencer#6]
Running functions such as `d` and `c` result in syntax errors. Here's the error for `d`:

```
expr: syntax error
read: Argument '-l' must be an integer
~/.local/share/omf/themes/budspencer/fish_prompt.fish (line 178):   read -p 'echo -n (set_color -b $budspencer_colors[2] $budspencer_colors[5])" ♻ Goto [e|0"$last_item"] "(set_color -b normal $budspencer_colors[2])" "(set_color $budspencer_colors[5])' -n $input_length -l dir_num
                                                                    ^
in function 'd'
	called on standard input


       read ‐‐ read line of input into variables

   Synopsis
       read [OPTIONS] [VARIABLES...]

read: Type 'help read' for related documentation

switch: Expected exactly one argument, got 0

~/.local/share/omf/themes/budspencer/fish_prompt.fish (line 23):   switch $dir_num                                                                       ^
```

**Comment by talha131** [comment]
I too am facing this issue. My fish version is `fish, version 2.2.0`.

**Comment by tannhuber** [comment]
This is probably due to incompatibilities with different `expr` versions. Budspencer uses `expr` for simple calculations. There's already a long discussion about calculations with fish, see https://github.com/fish-shell/fish-shell/issues/1643. I decided on `expr` because it's much faster than `bc`.

Can you tell me your `expr` version?
```
expr --version
```
will tell you. I use `expr` from GNU coreutils package. Probably you have a different version.

**Comment by predmijat** [comment]
Yes, by default on OS X `expr --version` produces `--version`. You need to install GNU coreutils - `brew install coreutils` and then tell OS X to use new `expr` instead of the default one. I did with `set PATH /usr/local/opt/coreutils/libexec/gnubin $PATH` in `~/.config/omf/init.fish` (it means "first try bins in gnubin"). If you want to replace only certain bins (like `expr`), you can symlink it.

**Comment by tannhuber** [comment]
Thank you.
